### ISSUE TITLE
org.apache.kafka.common.errors.InvalidSessionTimeoutException's no record information is available

### ISSUE THREAD

**Issue by whoiswentz** [Azure/azure-event-hubs-for-kafka#112]
Description
===========
I have two "microservices" made using Spring Boot, first, it's a producer that's run well and producer the messages, and the second it's a consumer that's should consume the messages made by the first. The problem is that the second don't consume the messages and throw this error ```java.lang.IllegalStateException: This error handler cannot process 'org.apache.kafka.common.errors.InvalidSessionTimeoutException's; no record information is available```

How to reproduce
================
I simply start two spring boot services with spring Kafka dependencies and configured these two projects with my Event Hubs for Kafka credentials. I used these two dependencies that can be seen below. My spring version it's the latest, so the dependencies too.
```xml
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter</artifactId>
</dependency>
<dependency>
    <groupId>org.springframework.kafka</groupId>
    <artifactId>spring-kafka</artifactId>
</dependency>
```
and the consumer and producer configuration
```properties
bootstrap.servers=XXX.servicebus.windows.net:9093
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://XXX-dev.servicebus.windows.net/; SharedAccessKeyName=XXX; SharedAccessKey=XXX";
sasl.mechanism=PLAIN
security.protocol=SASL_SSL
```
only consumer configuration
```java
configs.put(ConsumerConfig.GROUP_ID_CONFIG, groupId);
configs.put(ConsumerConfig.MAX_POLL_INTERVAL_MS_CONFIG, "5000");
configs.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest");
configs.put(ConsumerConfig.CLIENT_ID_CONFIG, UUID.randomUUID().toString());
configs.put(ErrorHandlingDeserializer.VALUE_DESERIALIZER_CLASS, JsonDeserializer.class.getName());
```
only producer configuration
```java
configs.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, StringSerializer.class);
configs.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, JsonSerializer.class);
configs.put(ProducerConfig.ACKS_CONFIG, "all");
```

the StackeTrace
```java
java.lang.IllegalStateException: This error handler cannot process 'org.apache.kafka.common.errors.InvalidSessionTimeoutException's; no record information is available
     at org.springframework.kafka.listener.SeekUtils.seekOrRecover(SeekUtils.java:151) ~[spring-kafka-2.5.2.RELEASE.jar:2.5.2.RELEASE]
     at org.springframework.kafka.listener.SeekToCurrentErrorHandler.handle(SeekToCurrentErrorHandler.java:103) ~[spring-kafka-2.5.2.RELEASE.jar:2.5.2.RELEASE]
     at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.handleConsumerException(KafkaMessageListenerContainer.java:1247) ~[spring-kafka-2.5.2.RELEASE.jar:2.5.2.RELEASE]
     at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1004) ~[spring-kafka-2.5.2.RELEASE.jar:2.5.2.RELEASE]
     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
     at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
     at java.base/java.lang.Thread.run(Thread.java:832) ~[na:na]
Caused by: org.apache.kafka.common.errors.InvalidSessionTimeoutException: The session timeout is not within the range allowed by the broker (as configured by group.min.session.timeout.ms and group.max.session.timeout.ms).

2020-07-22 17:09:28.017  INFO 2582630 --- [ntainer#0-0-C-1] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=ed3c3738-5b4d-4a83-8c19-76f0a11316bb-0, groupId=com.hi.servicemessagestatusprocessor.ServiceMessageStatusProcessorApplication] (Re-)joining group
2020-07-22 17:09:28.035 ERROR 2582630 --- [ntainer#0-0-C-1] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=ed3c3738-5b4d-4a83-8c19-76f0a11316bb-0, groupId=com.hi.servicemessagestatusprocessor.ServiceMessageStatusProcessorApplication] Attempt to join group failed due to fatal error: The session timeout is not within the range allowed by the broker (as configured by group.min.session.timeout.ms and group.max.session.timeout.ms).
2020-07-22 17:09:28.035  INFO 2582630 --- [ntainer#0-0-C-1] o.a.k.c.c.internals.AbstractCoordinator  : [Consumer clientId=ed3c3738-5b4d-4a83-8c19-76f0a11316bb-0, groupId=com.hi.servicemessagestatusprocessor.ServiceMessageStatusProcessorApplication] Join group failed with org.apache.kafka.common.errors.InvalidSessionTimeoutException: The session timeout is not within the range allowed by the broker (as configured by group.min.session.timeout.ms and group.max.session.timeout.ms).
2020-07-22 17:09:28.036 ERROR 2582630 --- [ntainer#0-0-C-1] essageListenerContainer$ListenerConsumer : Consumer exception
```

Has it worked previously?
=========================
No, the consume was never worked

**Comment by arerlend** [comment]
Can you try setting all recommended settings here?  Even for the producer - these settings resolve a number of common networking issues.

https://github.com/Azure/azure-event-hubs-for-kafka/blob/master/CONFIGURATION.md

**Comment by arerlend** [comment]
EH is returning this error since the session timeout set on the join group request is not between 6s and 300s.  Best way to resolve this is to follow recommended configs.

**Comment by whoiswentz** [comment]
I tried the recommended configuration, but still doesn't working :(

**Comment by whoiswentz** [comment]
This is my consumer configuration now

```java
configs.put(ConsumerConfig.GROUP_ID_CONFIG, groupId);
        configs.put(ConsumerConfig.MAX_POLL_INTERVAL_MS_CONFIG, "1");
        configs.put(ConsumerConfig.AUTO_OFFSET_RESET_CONFIG, "earliest");
        configs.put(ConsumerConfig.CLIENT_ID_CONFIG, UUID.randomUUID().toString());
        configs.put(ErrorHandlingDeserializer.VALUE_DESERIALIZER_CLASS, JsonDeserializer.class.getName());

        configs.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class);
        configs.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, JsonDeserializer.class);

        // Consumer and Producer configs
        configs.put(ConsumerConfig.METADATA_MAX_AGE_CONFIG, 180000);
        configs.put(ConsumerConfig.CONNECTIONS_MAX_IDLE_MS_CONFIG, 180000);

        // Consumer config only
        configs.put(ConsumerConfig.HEARTBEAT_INTERVAL_MS_CONFIG, 3000);
        configs.put(ConsumerConfig.SESSION_TIMEOUT_MS_CONFIG, 30000);

```

**Comment by whoiswentz** [comment]
The funny part is that I made a node.js consumer with the same configurations, and they consumed the messages, but here in the company the is a requirement to use java, more specifically spring boot

**Comment by whoiswentz** [comment]
I've been able to consume messages from local broker to, I think that the problem isn't on my consumer

**Comment by arerlend** [comment]
Interesting.  We only return invalid session timeout in one place but this config looks right.

Can you file a support ticket on the Azure portal with your namespace info?  We can provide a public resolution update here, but we should get your namespace + some timestamps to investigate.

**Comment by whoiswentz** [comment]
Ok, I will open a ticket, closing this issue
