### ISSUE TITLE
Unexpected error code 13 when committing offsets

### ISSUE THREAD

**Issue by RyanSept** [Azure/azure-event-hubs-for-kafka#118]
Description
===========
Every now and then, the server returns an error with code 13 when committing offsets from an Azure EventHubs topic via a Kafka client. The kafka-python SDK refers to this error as StaleLeaderEpochCodeError. The resolution on #31 which looks similar to this seemed unclear so I opened this ticket

```
2020-10-07T19:20:55.492650Z agent-ce13faf-912ad app - - - [E] 2020-10-07 19:20:55,481 aiokafka.consumer.group_coordinator OffsetCommit failed for group 1292881836027880489 on partition TopicPartition(topic='***', partition=8) with offset OffsetAndMetadata(offset=169616, metadata=''): StaleLeaderEpochCodeError
2020-10-07T19:20:55.492661Z agent-ce13faf-912ad app - - - [E] 2020-10-07 19:20:55,489 aiokafka.consumer.group_coordinator OffsetCommit failed for group 1292881836027880489 on partition TopicPartition(topic='***', partition=6) with offset OffsetAndMetadata(offset=169610, metadata=''): StaleLeaderEpochCodeError
2020-10-07T19:20:55.693141Z agent-ce13faf-912ad app - - - [E] 2020-10-07 19:20:55,495 aiokafka.consumer.group_coordinator OffsetCommit failed for group 1292881836027880489 on partition TopicPartition(topic='***', partition=10) with offset OffsetAndMetadata(offset=169607, metadata=''): StaleLeaderEpochCodeError
2020-10-07T19:20:55.693201Z agent-ce13faf-912ad app - - - [E] 2020-10-07 19:20:55,500 aiokafka.consumer.group_coordinator OffsetCommit failed for group 1292881836027880489 on partition TopicPartition(topic='***', partition=0) with offset OffsetAndMetadata(offset=169605, metadata=''): StaleLeaderEpochCodeError
2020-10-07T19:20:55.693209Z agent-ce13faf-912ad app - - - [E] 2020-10-07 19:20:55,505 agent/1292881836027880489 Unexpected error
2020-10-07T19:20:55.693215Z agent-ce13faf-912ad app - - - Traceback (most recent call last):
2020-10-07T19:20:55.693220Z agent-ce13faf-912ad app - - - File "***", line 224, in consume_forever
2020-10-07T19:20:55.693225Z agent-ce13faf-912ad app - - - await event_dispatcher(message)
2020-10-07T19:20:55.693230Z agent-ce13faf-912ad app - - - File "***", line 272, in handle_message
2020-10-07T19:20:55.693234Z agent-ce13faf-912ad app - - - await consumer.commit()
2020-10-07T19:20:55.693239Z agent-ce13faf-912ad app - - - File "/usr/local/lib/python3.7/dist-packages/aiokafka/consumer/consumer.py", line 548, in commit
2020-10-07T19:20:55.693243Z agent-ce13faf-912ad app - - - yield from self._coordinator.commit_offsets(assignment, offsets)
2020-10-07T19:20:55.693247Z agent-ce13faf-912ad app - - - File "/usr/local/lib/python3.7/dist-packages/aiokafka/consumer/group_coordinator.py", line 967, in commit_offsets
2020-10-07T19:20:55.693252Z agent-ce13faf-912ad app - - - raise err
2020-10-07T19:20:55.693257Z agent-ce13faf-912ad app - - - File "/usr/local/lib/python3.7/dist-packages/aiokafka/consumer/group_coordinator.py", line 957, in commit_offsets
2020-10-07T19:20:55.693262Z agent-ce13faf-912ad app - - - loop=self._loop)
2020-10-07T19:20:55.693267Z agent-ce13faf-912ad app - - - File "/usr/local/lib/python3.7/dist-packages/aiokafka/consumer/group_coordinator.py", line 1069, in _do_commit_offsets
2020-10-07T19:20:55.693271Z agent-ce13faf-912ad app - - - raise first_error
2020-10-07T19:20:55.693276Z agent-ce13faf-912ad app - - - kafka.errors.StaleLeaderEpochCodeError: [Error 13] StaleLeaderEpochCodeError
2020-10-07T19:20:55.693280Z agent-ce13faf-912ad app - - - [W] 2020-10-07 19:20:55,520 aiokafka.consumer.fetcher Unexpected error while fetching data: UnknownError
2020-10-07T19:20:55.693286Z agent-ce13faf-912ad app - - - [W] 2020-10-07 19:20:55,520 aiokafka.consumer.fetcher Unexpected error while fetching data: UnknownError
```

How to reproduce
================
Unable to reproduce programmatically.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed or where adequate information has not been provided.

Please provide the relevant information for the following items:
 - [x] SDK (include version info): `aiokafka-0.5.2 with kafka-python-1.4.6`
 - [x] Kafka client configuration: `
        max.poll.interval.ms=259200000
        group.id=1292881836027880489
        enable.auto.commit=false
        session.timeout.ms=30000
        request.timeout.ms=120000`
 - [x] Namespace and EventHub/topic name
 - [x] Consumer or producer failure `Consumer failure`
 - [x] Logs provided (with debug-level logging enabled if possible, e.g. log4j.rootLogger=DEBUG) or exception call stack
 - [x] Operating system: `Ubuntu 19.10`
 - [x] Critical issue

**Comment by arerlend** [comment]
@RyanSept error code 13 is occasionally returned by the broker as a NetworkException error code because it will trigger most Kafka SDKs to recognize a transient error and do a retry.  kafka-python has chosen not to update their error code 13 from StaleLeaderEpochCodeError to NetworkException, and that decision is actually reasonable, as the native Kafka broker doesn't explicitly return error code 13 - the network layers of Kafka clients just return error code 13 on network issues to upper layers in the client to trigger retry logic.

In this case, you should just catch the error and manually do a retry.
