### ISSUE TITLE
Unable to publish to event hub

### ISSUE THREAD

**Issue by uhdyi** [Azure/azure-event-hubs-for-kafka#230]
Description
===========
Unable to publish message to event hub, got error message:java.io.EOFException: EOF during handshake, handshake status is NEED_UNWRAP.

How to reproduce
================
cloned azure-event-hubs-for-kafka and produced msg using quickstart java producer

Has it worked previously?
=========================
its a first attempt

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed or where adequate information has not been provided.

Please provide the relevant information for the following items:
 - [ ] SDK (include version info): `Java SDK: OpenJDK 64-Bit Server VM Zulu17.36+14-SA (build 17.0.4+8-LTS, mixed mode, sharing)`
 - [ ] Sample you're having trouble with: `Java quickstart`
 - [x] If using Apache Kafka Java clients or a framework that uses Apache Kafka Java clients, version: `3.0.1`
 - [ ] Kafka client configuration: `<REPLACE with e.g., auto.reset.offset=earliest, ..>` (*do not include your connection string or SAS Key*)
 - [ ] Namespace and EventHub/topic name: s00199-enscdx-pd-us-payment-na1.servicebus.windows.net and evhcdx-payment-ingestion
 - [ ] Consumer or producer failure `Producer failure`
 - [ ] Timestamps *in UTC* `<REPLACE with e.g., Nov 7 2018 - 17:15:01 UTC>`
 - [ ] group.id or client.id `<REPLACE with e.g., group.id=cg-name>`
 - [ ] Logs provided (with debug-level logging enabled if possible, e.g. log4j.rootLogger=DEBUG) or exception call stack
 - [ ] Standalone repro `<REPLACE with e.g., Willing/able to send scenario to repro issue>`
 - [ ] Operating system: `macOS Monterey 12.6.2`
 - [ ] Critical issue

If this is a question on basic functionality, please verify the following:
 - [ ] Port 9093 should not be blocked by firewall ("broker cannot be found" errors)
 - [ ] Pinging FQDN should return cluster DNS resolution : its resolving dns
 - [ ] Namespace should be either Standard or Dedicated tier, not Basic : its standard tier

**Comment by uhdyi** [comment]
producer log: 
2023-01-10 22:17:36 INFO  ProducerConfig:376 - ProducerConfig values:
	acks = -1
	batch.size = 16384
	bootstrap.servers = [s00199-enscdx-pd-us-payment-na1.servicebus.windows.net:9093]
	buffer.memory = 33554432
	client.dns.lookup = use_all_dns_ips
	client.id = KafkaExampleProducer
	compression.type = none
	connections.max.idle.ms = 540000
	delivery.timeout.ms = 120000
	enable.idempotence = true
	interceptor.classes = []
	key.serializer = class org.apache.kafka.common.serialization.StringSerializer
	linger.ms = 0
	max.block.ms = 60000
	max.in.flight.requests.per.connection = 5
	max.request.size = 1048576
	metadata.max.age.ms = 300000
	metadata.max.idle.ms = 300000
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	partitioner.class = class org.apache.kafka.clients.producer.internals.DefaultPartitioner
	receive.buffer.bytes = 32768
	reconnect.backoff.max.ms = 1000
	reconnect.backoff.ms = 50
	request.timeout.ms = 30000
	retries = 2147483647
	retry.backoff.ms = 100
	sasl.client.callback.handler.class = null
	sasl.jaas.config = [hidden]
	sasl.kerberos.kinit.cmd = /usr/bin/kinit
	sasl.kerberos.min.time.before.relogin = 60000
	sasl.kerberos.service.name = null
	sasl.kerberos.ticket.renew.jitter = 0.05
	sasl.kerberos.ticket.renew.window.factor = 0.8
	sasl.login.callback.handler.class = null
	sasl.login.class = null
	sasl.login.refresh.buffer.seconds = 300
	sasl.login.refresh.min.period.seconds = 60
	sasl.login.refresh.window.factor = 0.8
	sasl.login.refresh.window.jitter = 0.05
	sasl.mechanism = PLAIN
	security.protocol = SASL_SSL
	security.providers = null
	send.buffer.bytes = 131072
	socket.connection.setup.timeout.max.ms = 30000
	socket.connection.setup.timeout.ms = 10000
	ssl.cipher.suites = null
	ssl.enabled.protocols = [TLSv1.2, TLSv1.3]
	ssl.endpoint.identification.algorithm = https
	ssl.engine.factory.class = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.certificate.chain = null
	ssl.keystore.key = null
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLSv1.3
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.certificates = null
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	transaction.timeout.ms = 60000
	transactional.id = null
	value.serializer = class org.apache.kafka.common.serialization.StringSerializer

2023-01-10 22:17:36 INFO  KafkaProducer:532 - [Producer clientId=KafkaExampleProducer] Instantiated an idempotent producer.
2023-01-10 22:17:36 INFO  AbstractLogin:61 - Successfully logged in.
2023-01-10 22:17:36 DEBUG DefaultSslEngineFactory:264 - Created SSL context with keystore null, truststore null, provider SunJSSE.
2023-01-10 22:17:36 DEBUG Sender:238 - [Producer clientId=KafkaExampleProducer] Starting Kafka producer I/O thread.
2023-01-10 22:17:36 DEBUG TransactionManager:1091 - [Producer clientId=KafkaExampleProducer] Transition from state UNINITIALIZED to INITIALIZING
2023-01-10 22:17:36 INFO  AppInfoParser:119 - Kafka version: 3.0.1
2023-01-10 22:17:36 INFO  AppInfoParser:120 - Kafka commitId: 8e30984f43e64d8b
2023-01-10 22:17:36 INFO  AppInfoParser:121 - Kafka startTimeMs: 1673417856709
2023-01-10 22:17:36 DEBUG KafkaProducer:434 - [Producer clientId=KafkaExampleProducer] Kafka producer started
2023-01-10 22:17:36 DEBUG TransactionManager:1129 - [Producer clientId=KafkaExampleProducer] Enqueuing transactional request InitProducerIdRequestData(transactionalId=null, transactionTimeoutMs=2147483647, producerId=-1, producerEpoch=-1)
2023-01-10 22:17:36 DEBUG NetworkClient:1151 - [Producer clientId=KafkaExampleProducer] Initialize connection to node s00199-enscdx-pd-us-payment-na1.servicebus.windows.net:9093 (id: -1 rack: null) for sending metadata request
2023-01-10 22:17:36 DEBUG ClientUtils:113 - Resolved host s00199-enscdx-pd-us-payment-na1.servicebus.windows.net as 191.1.129.16
2023-01-10 22:17:36 DEBUG NetworkClient:980 - [Producer clientId=KafkaExampleProducer] Initiating connection to node s00199-enscdx-pd-us-payment-na1.servicebus.windows.net:9093 (id: -1 rack: null) using address s00199-enscdx-pd-us-payment-na1.servicebus.windows.net/191.1.129.16
2023-01-10 22:17:36 DEBUG SaslClientAuthenticator:411 - [Producer clientId=KafkaExampleProducer] Set SASL client state to SEND_APIVERSIONS_REQUEST
2023-01-10 22:17:36 DEBUG SaslClientAuthenticator:217 - [Producer clientId=KafkaExampleProducer] Creating SaslClient: client=null;service=kafka;serviceHostname=s00199-enscdx-pd-us-payment-na1.servicebus.windows.net;mechs=[PLAIN]
2023-01-10 22:17:36 DEBUG Selector:531 - [Producer clientId=KafkaExampleProducer] Created socket with SO_RCVBUF = 32768, SO_SNDBUF = 131072, SO_TIMEOUT = 0 to node -1
2023-01-10 22:17:36 DEBUG NetworkClient:942 - [Producer clientId=KafkaExampleProducer] Completed connection to node -1. Fetching API versions.
Test Data #0 from thread #20
2023-01-10 22:17:47 DEBUG SslTransportLayer:198 - [SslTransportLayer channelId=-1 key=channel=java.nio.channels.SocketChannel[connection-pending remote=s00199-enscdx-pd-us-payment-na1.servicebus.windows.net/191.1.129.16:9093], selector=sun.nio.ch.KQueueSelectorImpl@5603a6ad, interestOps=8, readyOps=0] Failed to send SSL Close message
java.io.IOException: Unexpected status returned by SSLEngine.wrap, expected CLOSED, received OK. Will not send close message to peer.
	at org.apache.kafka.common.network.SslTransportLayer.close(SslTransportLayer.java:192)
	at org.apache.kafka.common.utils.Utils.closeAll(Utils.java:972)
	at org.apache.kafka.common.network.KafkaChannel.close(KafkaChannel.java:155)
	at org.apache.kafka.common.network.Selector.doClose(Selector.java:955)
	at org.apache.kafka.common.network.Selector.close(Selector.java:939)
	at org.apache.kafka.common.network.Selector.close(Selector.java:885)
	at org.apache.kafka.clients.NetworkClient.handleTimedOutConnections(NetworkClient.java:809)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:564)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:74)
	at org.apache.kafka.clients.producer.internals.Sender.awaitNodeReady(Sender.java:526)
	at org.apache.kafka.clients.producer.internals.Sender.maybeSendAndPollTransactionalRequest(Sender.java:447)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:316)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:243)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-01-10 22:17:47 DEBUG NetworkClient:810 - [Producer clientId=KafkaExampleProducer] Disconnecting from node -1 due to socket connection setup timeout. The timeout value is 10276 ms.
2023-01-10 22:17:47 WARN  NetworkClient:1054 - [Producer clientId=KafkaExampleProducer] Bootstrap broker s00199-enscdx-pd-us-payment-na1.servicebus.windows.net:9093 (id: -1 rack: null) disconnected
2023-01-10 22:17:47 DEBUG Sender:475 - [Producer clientId=KafkaExampleProducer] Disconnect from s00199-enscdx-pd-us-payment-na1.servicebus.windows.net:9093 (id: -1 rack: null) while trying to send request InitProducerIdRequestData(transactionalId=null, transactionTimeoutMs=2147483647, producerId=-1, producerEpoch=-1). Going to back off and retry.
java.io.IOException: Connection to s00199-enscdx-pd-us-payment-na1.servicebus.windows.net:9093 (id: -1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at org.apache.kafka.clients.producer.internals.Sender.awaitNodeReady(Sender.java:526)
	at org.apache.kafka.clients.producer.internals.Sender.maybeSendAndPollTransactionalRequest(Sender.java:447)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:316)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:243)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-01-10 22:17:47 DEBUG TransactionManager:1129 - [Producer clientId=KafkaExampleProducer] Enqueuing transactional request InitProducerIdRequestData(transactionalId=null, transactionTimeoutMs=2147483647, producerId=-1, producerEpoch=-1)
2023-01-10 22:17:47 DEBUG NetworkClient:1151 - [Producer clientId=KafkaExampleProducer] Initialize connection to node s00199-enscdx-pd-us-payment-na1.servicebus.windows.net:9093 (id: -1 rack: null) for sending metadata request
2023-01-10 22:17:47 DEBUG ClientUtils:113 - Resolved host s00199-enscdx-pd-us-payment-na1.servicebus.windows.net as 191.1.129.16
2023-01-10 22:17:47 DEBUG NetworkClient:980 - [Producer clientId=KafkaExampleProducer] Initiating connection to node s00199-enscdx-pd-us-payment-na1.servicebus.windows.net:9093 (id: -1 rack: null) using address s00199-enscdx-pd-us-payment-na1.servicebus.windows.net/191.1.129.16
2023-01-10 22:17:47 DEBUG SaslClientAuthenticator:411 - [Producer clientId=KafkaExampleProducer] Set SASL client state to SEND_APIVERSIONS_REQUEST
2023-01-10 22:17:47 DEBUG SaslClientAuthenticator:217 - [Producer clientId=KafkaExampleProducer] Creating SaslClient: client=null;service=kafka;serviceHostname=s00199-enscdx-pd-us-payment-na1.servicebus.windows.net;mechs=[PLAIN]
2023-01-10 22:17:47 DEBUG Selector:531 - [Producer clientId=KafkaExampleProducer] Created socket with SO_RCVBUF = 32768, SO_SNDBUF = 131072, SO_TIMEOUT = 0 to node -1
2023-01-10 22:17:47 DEBUG NetworkClient:942 - [Producer clientId=KafkaExampleProducer] Completed connection to node -1. Fetching API versions.
2023-01-10 22:18:04 DEBUG SslTransportLayer:198 - [SslTransportLayer channelId=-1 key=channel=java.nio.channels.SocketChannel[connection-pending remote=s00199-enscdx-pd-us-payment-na1.servicebus.windows.net/191.1.129.16:9093], selector=sun.nio.ch.KQueueSelectorImpl@5603a6ad, interestOps=8, readyOps=0] Failed to send SSL Close message
java.io.IOException: Unexpected status returned by SSLEngine.wrap, expected CLOSED, received OK. Will not send close message to peer.
	at org.apache.kafka.common.network.SslTransportLayer.close(SslTransportLayer.java:192)
	at org.apache.kafka.common.utils.Utils.closeAll(Utils.java:972)
	at org.apache.kafka.common.network.KafkaChannel.close(KafkaChannel.java:155)
	at org.apache.kafka.common.network.Selector.doClose(Selector.java:955)
	at org.apache.kafka.common.network.Selector.close(Selector.java:939)
	at org.apache.kafka.common.network.Selector.close(Selector.java:885)
	at org.apache.kafka.clients.NetworkClient.handleTimedOutConnections(NetworkClient.java:809)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:564)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:74)
	at org.apache.kafka.clients.producer.internals.Sender.awaitNodeReady(Sender.java:526)
	at org.apache.kafka.clients.producer.internals.Sender.maybeSendAndPollTransactionalRequest(Sender.java:447)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:316)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:243)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-01-10 22:18:04 DEBUG NetworkClient:810 - [Producer clientId=KafkaExampleProducer] Disconnecting from node -1 due to socket connection setup timeout. The timeout value is 17496 ms.
2023-01-10 22:18:04 WARN  NetworkClient:1054 - [Producer clientId=KafkaExampleProducer] Bootstrap broker s00199-enscdx-pd-us-payment-na1.servicebus.windows.net:9093 (id: -1 rack: null) disconnected
2023-01-10 22:18:04 DEBUG Sender:475 - [Producer clientId=KafkaExampleProducer] Disconnect from s00199-enscdx-pd-us-payment-na1.servicebus.windows.net:9093 (id: -1 rack: null) while trying to send request InitProducerIdRequestData(transactionalId=null, transactionTimeoutMs=2147483647, producerId=-1, producerEpoch=-1). Going to back off and retry.
java.io.IOException: Connection to s00199-enscdx-pd-us-payment-na1.servicebus.windows.net:9093 (id: -1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at org.apache.kafka.clients.producer.internals.Sender.awaitNodeReady(Sender.java:526)
	at org.apache.kafka.clients.producer.internals.Sender.maybeSendAndPollTransactionalRequest(Sender.java:447)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:316)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:243)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-01-10 22:18:04 DEBUG TransactionManager:1129 - [Producer clientId=KafkaExampleProducer] Enqueuing transactional request InitProducerIdRequestData(transactionalId=null, transactionTimeoutMs=2147483647, producerId=-1, producerEpoch=-1)
2023-01-10 22:18:04 DEBUG NetworkClient:1151 - [Producer clientId=KafkaExampleProducer] Initialize connection to node s00199-enscdx-pd-us-payment-na1.servicebus.windows.net:9093 (id: -1 rack: null) for sending metadata request
2023-01-10 22:18:04 DEBUG ClientUtils:113 - Resolved host s00199-enscdx-pd-us-payment-na1.servicebus.windows.net as 191.1.129.16
2023-01-10 22:18:04 DEBUG NetworkClient:980 - [Producer clientId=KafkaExampleProducer] Initiating connection to node s00199-enscdx-pd-us-payment-na1.servicebus.windows.net:9093 (id: -1 rack: null) using address s00199-enscdx-pd-us-payment-na1.servicebus.windows.net/191.1.129.16
2023-01-10 22:18:04 DEBUG SaslClientAuthenticator:411 - [Producer clientId=KafkaExampleProducer] Set SASL client state to SEND_APIVERSIONS_REQUEST
2023-01-10 22:18:04 DEBUG SaslClientAuthenticator:217 - [Producer clientId=KafkaExampleProducer] Creating SaslClient: client=null;service=kafka;serviceHostname=s00199-enscdx-pd-us-payment-na1.servicebus.windows.net;mechs=[PLAIN]
2023-01-10 22:18:04 DEBUG Selector:531 - [Producer clientId=KafkaExampleProducer] Created socket with SO_RCVBUF = 32768, SO_SNDBUF = 131072, SO_TIMEOUT = 0 to node -1
2023-01-10 22:18:04 DEBUG NetworkClient:942 - [Producer clientId=KafkaExampleProducer] Completed connection to node -1. Fetching API versions.
2023-01-10 22:18:23 DEBUG Selector:606 - [Producer clientId=KafkaExampleProducer] Connection with s00199-enscdx-pd-us-payment-na1.servicebus.windows.net/191.1.129.16 disconnected
java.io.EOFException: EOF during handshake, handshake status is NEED_UNWRAP
	at org.apache.kafka.common.network.SslTransportLayer.handshakeUnwrap(SslTransportLayer.java:525)
	at org.apache.kafka.common.network.SslTransportLayer.doHandshake(SslTransportLayer.java:368)
	at org.apache.kafka.common.network.SslTransportLayer.handshake(SslTransportLayer.java:291)
	at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:178)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:543)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:551)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:74)
	at org.apache.kafka.clients.producer.internals.Sender.awaitNodeReady(Sender.java:526)
	at org.apache.kafka.clients.producer.internals.Sender.maybeSendAndPollTransactionalRequest(Sender.java:447)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:316)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:243)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-01-10 22:18:23 DEBUG SslTransportLayer:198 - [SslTransportLayer channelId=-1 key=channel=java.nio.channels.SocketChannel[connection-pending remote=s00199-enscdx-pd-us-payment-na1.servicebus.windows.net/191.1.129.16:9093], selector=sun.nio.ch.KQueueSelectorImpl@5603a6ad, interestOps=8, readyOps=0] Failed to send SSL Close message
java.io.IOException: Unexpected status returned by SSLEngine.wrap, expected CLOSED, received OK. Will not send close message to peer.
	at org.apache.kafka.common.network.SslTransportLayer.close(SslTransportLayer.java:192)
	at org.apache.kafka.common.utils.Utils.closeAll(Utils.java:972)
	at org.apache.kafka.common.network.KafkaChannel.close(KafkaChannel.java:155)
	at org.apache.kafka.common.network.Selector.doClose(Selector.java:955)
	at org.apache.kafka.common.network.Selector.close(Selector.java:939)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:625)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:481)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:551)
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:74)
	at org.apache.kafka.clients.producer.internals.Sender.awaitNodeReady(Sender.java:526)
	at org.apache.kafka.clients.producer.internals.Sender.maybeSendAndPollTransactionalRequest(Sender.java:447)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:316)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:243)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-01-10 22:18:23 DEBUG NetworkClient:926 - [Producer clientId=KafkaExampleProducer] Node -1 disconnected.
2023-01-10 22:18:23 WARN  NetworkClient:759 - [Producer clientId=KafkaExampleProducer] Connection to node -1 (s00199-enscdx-pd-us-payment-na1.servicebus.windows.net/191.1.129.16:9093) terminated during authentication. This may happen due to any of the following reasons: (1) Authentication failed due to invalid credentials with brokers older than 1.0.0, (2) Firewall blocking Kafka TLS traffic (eg it may only allow HTTPS traffic), (3) Transient network issue.
2023-01-10 22:18:23 WARN  NetworkClient:1054 - [Producer clientId=KafkaExampleProducer] Bootstrap broker s00199-enscdx-pd-us-payment-na1.servicebus.windows.net:9093 (id: -1 rack: null) disconnected
2023-01-10 22:18:23 DEBUG Sender:475 - [Producer clientId=KafkaExampleProducer] Disconnect from s00199-enscdx-pd-us-payment-na1.servicebus.windows.net:9093 (id: -1 rack: null) while trying to send request InitProducerIdRequestData(transactionalId=null, transactionTimeoutMs=2147483647, producerId=-1, producerEpoch=-1). Going to back off and retry.
java.io.IOException: Connection to s00199-enscdx-pd-us-payment-na1.servicebus.windows.net:9093 (id: -1 rack: null) failed.
	at org.apache.kafka.clients.NetworkClientUtils.awaitReady(NetworkClientUtils.java:71)
	at org.apache.kafka.clients.producer.internals.Sender.awaitNodeReady(Sender.java:526)
	at org.apache.kafka.clients.producer.internals.Sender.maybeSendAndPollTransactionalRequest(Sender.java:447)
	at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:316)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:243)
	at java.base/java.lang.Thread.run(Thread.java:833)
2023-01-10 22:18:23 DEBUG TransactionManager:1129 - [Producer clientId=KafkaExampleProducer] Enqueuing transactional request InitProducerIdRequestData(transactionalId=null, transactionTimeoutMs=2147483647, producerId=-1, producerEpoch=-1)
2023-01-10 22:18:23 DEBUG TransactionManager:1129 - [Producer clientId=KafkaExampleProducer] Enqueuing transactional request InitProducerIdRequestData(transactionalId=null, transactionTimeoutMs=2147483647, producerId=-1, producerEpoch=-1)
2023-01-10 22:18:23 DEBUG NetworkClient:1036 - [Producer clientId=KafkaExampleProducer] Give up sending metadata request since no node is available
2023-01-10 22:18:23 DEBUG TransactionManager:1129 - [Producer clientId=KafkaExampleProducer] Enqueuing transactional request InitProducerIdRequestData(transactionalId=null, transactionTimeoutMs=2147483647, producerId=-1, producerEpoch=-1)
2023-01-10 22:18:23 DEBUG NetworkClient:1036 - [Producer clientId=KafkaExampleProducer] Give up sending metadata request since no node is available
2023-01-10 22:18:23 DEBUG NetworkClient:1151 - [Producer clientId=KafkaExampleProducer] Initialize connection to node s00199-enscdx-pd-us-payment-na1.servicebus.windows.net:9093 (id: -1 rack: null) for sending metadata request
2023-01-10 22:18:23 DEBUG ClientUtils:113 - Resolved host s00199-enscdx-pd-us-payment-na1.servicebus.windows.net as 191.1.129.16
2023-01-10 22:18:23 DEBUG NetworkClient:980 - [Producer clientId=KafkaExampleProducer] Initiating connection to node s00199-enscdx-pd-us-payment-na1.servicebus.windows.net:9093 (id: -1 rack: null) using address s00199-enscdx-pd-us-payment-na1.servicebus.windows.net/191.1.129.16
2023-01-10 22:18:23 DEBUG SaslClientAuthenticator:411 - [Producer clientId=KafkaExampleProducer] Set SASL client state to SEND_APIVERSIONS_REQUEST
2023-01-10 22:18:23 DEBUG SaslClientAuthenticator:217 - [Producer clientId=KafkaExampleProducer] Creating SaslClient: client=null;service=kafka;serviceHostname=s00199-enscdx-pd-us-payment-na1.servicebus.windows.net;mechs=[PLAIN]
2023-01-10 22:18:23 DEBUG Selector:531 - [Producer clientId=KafkaExampleProducer] Created socket with SO_RCVBUF = 32768, SO_SNDBUF = 131072, SO_TIMEOUT = 0 to node -1
2023-01-10 22:18:23 DEBUG NetworkClient:942 - [Producer clientId=KafkaExampleProducer] Completed connection to node -1. Fetching API versions.
2023-01-10 22:18:41 DEBUG KafkaProducer:956 - [Producer clientId=KafkaExampleProducer] Exception occurred during message send:
org.apache.kafka.common.errors.TimeoutException: Topic evhcdx-payment-ingestion not present in metadata after 60000 ms.
org.apache.kafka.common.errors.TimeoutException: Topic evhcdx-payment-ingestion not present in metadata after 60000 ms.

**Comment by nhathatrinh** [comment]
I am having same issue when connect to Kafka Event Hubs SASL_SSL. I wonder if there is any solution for this issue?

2024-09-20 08:25:38.986Z DEBUG [kafka-producer-network-thread | xxxeventhubs[1]] o.a.k.c.network.SslTransportLayer - [SslTransportLayer channelId=-1 key=channel=java.nio.channels.SocketChannel[connection-pending remote=export-event-hub.servicebus.windows.net/xxx.xxx.45.161:9093], selector=sun.nio.ch.EPollSelectorImpl@2653d023, interestOps=8, readyOps=0] Failed to send SSL Close message
java.io.IOException: Unexpected status returned by SSLEngine.wrap, expected CLOSED, received OK. Will not send close message to peer.
        at org.apache.kafka.common.network.SslTransportLayer.close(SslTransportLayer.java:194)
        at org.apache.kafka.common.utils.Utils.closeAll(Utils.java:989)
        at org.apache.kafka.common.network.KafkaChannel.close(KafkaChannel.java:155)
        at org.apache.kafka.common.network.Selector.doClose(Selector.java:956)
        at org.apache.kafka.common.network.Selector.close(Selector.java:940)
        at org.apache.kafka.common.network.Selector.close(Selector.java:886)
        at org.apache.kafka.clients.NetworkClient.handleTimedOutConnections(NetworkClient.java:818)
        at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:573)
        at org.apache.kafka.clients.producer.internals.Sender.runOnce(Sender.java:328)
        at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:243)
        at java.base/java.lang.Thread.run(Thread.java:840)
