### ISSUE TITLE
Unexpected error code 9 while fetching data

### ISSUE THREAD

**Issue by hiashishkm** [Azure/azure-event-hubs-for-kafka#231]
Hi team,

MySpring-boot application uses spring integration based Kafka client to connect to Azure event hub for retrieving or publishing messages. This application was running fine since 450 days as a containerized application shipping logs to Azure app insights and there were no issues reported. 

Spring boot version - 1.5.8.RELEASE
Spring integration kafka dependency -
<groupId>org.springframework.integration</groupId>
    <artifactId>spring-integration-kafka</artifactId>
	<version>2.3.0.RELEASE</version>

We started seeing a huge spike in the logs with the following error  -
java.lang.IllegalStateException: **Unexpected error code 9 while fetching data**
        at org.apache.kafka.clients.consumer.internals.Fetcher.parseCompletedFetch(Fetcher.java:886)
        at org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:525)
        at org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1086)
        at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1043)
        at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:614)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:748) 

Previously saw similar errors related to error code 13 posted on this forum hence posting this issue as well to get a resolution

**Comment by Nikh1l** [comment]
Facing the same issue for a couple of weeks now. 

Spring boot version: 2.0.8.RELEASE
Kafka: org.springframework.integration:spring-integration-kafka:3.0.3.RELEASE

java.lang.IllegalStateException: Unexpected error code 9 while fetching data
org.apache.kafka.clients.consumer.internals.Fetcher.parseCompletedFetch(Fetcher.java:891)
org.apache.kafka.clients.consumer.internals.Fetcher.fetchedRecords(Fetcher.java:528)
org.apache.kafka.clients.consumer.KafkaConsumer.pollOnce(KafkaConsumer.java:1154)
org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1111)
org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:723)
java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
java.util.concurrent.FutureTask.run(FutureTask.java:266)\n\tat java.lang.Thread.run(Thread.java:750)
