### ISSUE TITLE
Unable to Establish Kafka Streams Connection

### ISSUE THREAD

**Issue by bykbrian** [Azure/azure-event-hubs-for-kafka#24]
Description
===========
Using standard producers I can write to topics but a Kafka Streams based application with same stack and configuration is unable to establish a connection with the Event Hub due to unexpected connection termination from the server side.

Here is the critical point, full log in [separate attachment](https://github.com/Azure/azure-event-hubs-for-kafka/files/2614674/kafka.log):

```
16:31:43.384 [myapp-92de0939-2ca5-4593-8d3e-2d83380ffd38-StreamThread-1] DEBUG o.a.kafka.common.network.Selector - [Consumer clientId=myapp-92de0939-2ca5-4593-8d3e-2d83380ffd38-StreamThread-1-consumer, groupId=myapp] Connection with <redacted>.servicebus.windows.net/40.78.234.0 disconnected
java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.apache.kafka.common.network.SslTransportLayer.readFromSocketChannel(SslTransportLayer.java:205)
	at org.apache.kafka.common.network.SslTransportLayer.read(SslTransportLayer.java:522)
	at org.apache.kafka.common.network.NetworkReceive.readFrom(NetworkReceive.java:94)
	at org.apache.kafka.common.network.KafkaChannel.receive(KafkaChannel.java:335)
	at org.apache.kafka.common.network.KafkaChannel.read(KafkaChannel.java:296)
	at org.apache.kafka.common.network.Selector.attemptRead(Selector.java:562)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:498)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:427)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:510)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:271)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:242)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:218)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:413)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:352)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:337)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:343)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1218)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1175)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1154)
	at org.apache.kafka.streams.processor.internals.StreamThread.pollRequests(StreamThread.java:861)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:810)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:767)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:736)
16:31:43.386 [myapp-92de0939-2ca5-4593-8d3e-2d83380ffd38-StreamThread-1] DEBUG o.a.k.c.network.SslTransportLayer - [SslTransportLayer channelId=2147483647 key=sun.nio.ch.SelectionKeyImpl@2e796acb] Failed to send SSL Close message
java.io.IOException: Broken pipe
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:65)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at org.apache.kafka.common.network.SslTransportLayer.flush(SslTransportLayer.java:218)
	at org.apache.kafka.common.network.SslTransportLayer.close(SslTransportLayer.java:178)
	at org.apache.kafka.common.utils.Utils.closeAll(Utils.java:807)
	at org.apache.kafka.common.network.KafkaChannel.close(KafkaChannel.java:107)
	at org.apache.kafka.common.network.Selector.doClose(Selector.java:753)
	at org.apache.kafka.common.network.Selector.close(Selector.java:741)
	at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:537)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:427)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:510)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:271)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:242)
	at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:218)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.joinGroupIfNeeded(AbstractCoordinator.java:413)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:352)
	at org.apache.kafka.clients.consumer.internals.AbstractCoordinator.ensureActiveGroup(AbstractCoordinator.java:337)
	at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.poll(ConsumerCoordinator.java:343)
	at org.apache.kafka.clients.consumer.KafkaConsumer.updateAssignmentMetadataIfNeeded(KafkaConsumer.java:1218)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1175)
	at org.apache.kafka.clients.consumer.KafkaConsumer.poll(KafkaConsumer.java:1154)
	at org.apache.kafka.streams.processor.internals.StreamThread.pollRequests(StreamThread.java:861)
	at org.apache.kafka.streams.processor.internals.StreamThread.runOnce(StreamThread.java:810)
	at org.apache.kafka.streams.processor.internals.StreamThread.runLoop(StreamThread.java:767)
	at org.apache.kafka.streams.processor.internals.StreamThread.run(StreamThread.java:736)
16:31:43.386 [myapp-92de0939-2ca5-4593-8d3e-2d83380ffd38-StreamThread-1] DEBUG o.apache.kafka.clients.NetworkClient - [Consumer clientId=myapp-92de0939-2ca5-4593-8d3e-2d83380ffd38-StreamThread-1-consumer, groupId=myapp] Node 2147483647 disconnected.
16:31:43.390 [myapp-92de0939-2ca5-4593-8d3e-2d83380ffd38-StreamThread-1] DEBUG o.a.k.c.c.i.ConsumerNetworkClient - [Consumer clientId=myapp-92de0939-2ca5-4593-8d3e-2d83380ffd38-StreamThread-1-consumer, groupId=myapp] Cancelled request with header RequestHeader(apiKey=JOIN_GROUP, apiVersion=2, clientId=myapp-92de0939-2ca5-4593-8d3e-2d83380ffd38-StreamThread-1-consumer, correlationId=9) due to node 2147483647 being disconnected
```

Has it worked previously?
=========================
Not with Kafka Streams but works fine with regular Kafka Producer.

Checklist
========= 
 - [x] Verified that port 9093 is not blocked by firewall
 - [x] Verified the namespace is either Standard or Dedicated tier (i.e. it is not Basic tier, which isn't supported)
 - [x] Sample you're having trouble with: `custom Kafka Streams app`
 - [x] Apache Kafka version: `2.0.1`
 - [x] Kafka client configuration: `bootstrap.servers = "<redacted>.servicebus.windows.net:9093", auto.offset.reset = "earliest", security.protocol = SASL_SSL, sasl.mechanism = PLAIN, sasl.jaas.config = "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"$ConnectionString\" password=\"Endpoint=sb://<redacted>.servicebus.windows.net/;SharedAccessKeyName=<redacted>;SharedAccessKey=<redacted>\";"`
 - [x] Namespace and EventHub/topic name: `oldendorff/ais-live`
 - [x] Consumer or producer failure `Producer Failure`
 - [x] Timestamp in UTC `Nov 26 08:31:09 2018` 
 - [x] Client ID `N/A (not set)`
 - [x] Provide all logs (with debugging enabled if possible) or exception call stack: [attached](https://github.com/Azure/azure-event-hubs-for-kafka/files/2614674/kafka.log)
 - [x] Standalone repro `N/A`
 - [x] Operating system: `Ubuntu 18.10`
 - [x] Critical issue

**Comment by MarkRBM** [comment]
Is there / will there be any announcement on progress towards this feature being implemented any time soon? We are in the process of moving our kafka installation to azure and becuase of this handicap we are being forced to consider the hdinsights offering of kafka which comes with a lot of unnecessary cost as we do not use hadoop.

**Comment by arerlend** [comment]
@sjkwak

**Comment by MarkRBM** [comment]
any information on this would be great as we enter into talks with Confluent about their cloud solution it would be great to know whats coming down the line and when with event hubs for kafka

**Comment by sjkwak** [comment]
Hi @MarkRBM we currently don't have a concrete timeline yet, but we expect it will be ready by late summer.

**Comment by MarkRBM** [comment]
this is very good news, thank you, might the answer be the same for the other currently unsupported kafka features or they all have individual timelines?

**Comment by hbensalem** [comment]
> Hi @MarkRBM we currently don't have a concrete timeline yet, but we expect it will be ready by late summer.

Hi @sjkwak  Any updates on this feature please ?

**Comment by jfgosselin** [comment]
Hi @sjkwak I'm also interested in this feature, any updates ?

**Comment by iam-kanavsharma** [comment]
Hi, Any updates on this please. I see the documentation still mentions that the feature is not supported but my application is able to produce and consume using Kafka Streams.

I want to ensure I can take this application to production. Thanks.

> @bykbrian - unfortunately the Streams API isn't supported yet. You can find more info at the link below.
> 
> https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-for-kafka-ecosystem-overview#features-that-are-not-yet-supported



> Hi @MarkRBM we currently don't have a concrete timeline yet, but we expect it will be ready by late summer.
