### ISSUE TITLE
Debezium SqlServer connector cannot create its own topics on azure-event-hubs but Kafka Connect can

### ISSUE THREAD

**Issue by vincent1405** [Azure/azure-event-hubs-for-kafka#241]
Description
===========
We are trying to enable Change Data Capture on our On Prem SQL Serve DB, and stream change events to Azure Event Hubs.
To do that, we launch connect-distributed.cmd with a connect-distributed.properties file to stream into Azure Event Hub.

Kafka Connect manages to create its "system" topics, but once we POST the SQL Server connector configuration via the Connect REST API, Kafka Connect keeps complaining it cannot connect to EH:
```java
[2023-05-26 15:16:35,507] INFO [missions-connector|task-0] [Producer clientId=gte_missions-schemahistory] Cancelled in-flight API_VERSIONS request with correlation id 364 due to node -1 being disconnected (elapsed time since creation: 16ms, elapsed time since send: 16ms, request timeout: 30000ms) (org.apache.kafka.clients.NetworkClient:341)
[2023-05-26 15:16:35,507] WARN [missions-connector|task-0] [Producer clientId=gte_missions-schemahistory] Bootstrap broker *******.servicebus.windows.net:9093 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient:1065)
[2023-05-26 15:16:35,585] INFO [missions-connector|task-0] [Producer clientId=gte_missions-schemahistory] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:937)
```

How to reproduce
================

1. Create a subfolder in the _kafka directory,_ e.g. _connect/plugins_, and copy the directory containing the SQL Server Debezium Connector.

2. Use the following properties file and save it as _connect-eh.properties_ in the _config_ directory:
```properties
bootstrap.servers=*******.servicebus.windows.net:9093 
group.id=*********-cdc-group

# connect internal topic names, auto-created if not exists
config.storage.topic=*********-cdc-group-configs
offset.storage.topic=*********-cdc-group-offsets
status.storage.topic=*********-cdc-group-status

# internal topic replication factors - auto 3x replication in Azure Storage
config.storage.replication.factor=1
offset.storage.replication.factor=1
status.storage.replication.factor=1

rest.advertised.host.name=connect
offset.flush.interval.ms=10000

key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter

internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false

# required EH Kafka security settings
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://*******.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=????????????";

producer.security.protocol=SASL_SSL
producer.sasl.mechanism=PLAIN
producer.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://*******.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=????????????";

consumer.security.protocol=SASL_SSL
consumer.sasl.mechanism=PLAIN
consumer.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="$ConnectionString" password="Endpoint=sb://*******.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=??????????";

plugin.path=connect/plugins
```

3. Once you launch the Kafka Connect by typing in a console:
```batch
bin\windows\connect-distributed.bat config\connect-event-hub.properties
```
You will see that Azure Event Hubs creates the "system" topics:
```properties
config.storage.topic=*********-cdc-group-configs
offset.storage.topic=*********-cdc-group-offsets
status.storage.topic=*********-cdc-group-status
```

4. Use POSTMAN, CURL, or any REST Client and POST the following JSON to http://localhost:8083/connectors/:
```json
{
    "name": "missions-connector", 
    "config": {
        "connector.class": "io.debezium.connector.sqlserver.SqlServerConnector", 
        "database.hostname": "DB_SERVER", 
        "database.port": "1433", 
        "database.user": "db_user", 
        "database.password": "******", 
        "database.server.name":"SERVER_NAME",
        "database.names": "DB_NAME",		
		"database.history.internal.kafka.bootstrap.servers": "*******.servicebus.windows.net:9093",
		"database.history.internal.kafka.topic": "datahistory",		
		"database.history.consumer.security.protocol": "SASL_SSL",
		"database.history.consumer.sasl.mechanism": "PLAIN",
		"database.history.consumer.sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"$ConnectionString\" password=\"Endpoint=sb://*******.servicebus.windows.net/;SharedAccessKeyName=Manage;SharedAccessKey=*******\";",		
		"database.history.producer.security.protocol": "SASL_SSL",
		"database.history.producer.sasl.mechanism": "PLAIN",
		"database.history.producer.sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"$ConnectionString\" password=\"Endpoint=sb://*******.servicebus.windows.net/;SharedAccessKeyName=Manage;SharedAccessKey=*******\";",
        "topic.prefix": "missions", 
        "table.include.list": "dbo.******", 		
        "schema.history.internal.kafka.bootstrap.servers": "*******.servicebus.windows.net:9093",         
        "schema.history.internal.kafka.topic":"schemahistory",		
		"schema.history.consumer.security.protocol": "SASL_SSL",		
		"schema.history.consumer.sasl.mechanism": "PLAIN",
		"schema.history.consumer.sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"$ConnectionString\" password=\"Endpoint=sb://*******.servicebus.windows.net/;SharedAccessKeyName=Manage;SharedAccessKey=*******\";",		
		"schema.history.producer.security.protocol": "SASL_SSL",		
		"schema.history.producer.sasl.mechanism": "PLAIN",
		"schema.history.producer.sasl.jaas.config": "org.apache.kafka.common.security.plain.PlainLoginModule required username=\"$ConnectionString\" password=\"Endpoint=sb://*******.servicebus.windows.net/;SharedAccessKeyName=Manage;SharedAccessKey=*******\";",
        "driver.trustServerCertificate": "true",
        "transforms": "Reroute",
        "transforms.Reroute.type": "io.debezium.transforms.ByLogicalTableRouter",
        "transforms.Reroute.topic.regex": "(.*)",
        "transforms.Reroute.topic.replacement": "gte_missions",
        "tombstones.on.delete": false,
        "database.history":"io.debezium.relational.history.MemoryDatabaseHistory"
    }
}

```

5. You will see that Kafka Connect does not manage to create db related topics:
```java
[2023-05-26 15:16:35,585] INFO [missions-connector|task-0] [Producer clientId=gte_missions-schemahistory] Cancelled in-flight API_VERSIONS request with correlation id 33 due to node -1 being disconnected (elapsed time since creation: 16ms, elapsed time since send: 16ms, request timeout: 30000ms) (org.apache.kafka.clients.NetworkClient:341)
[2023-05-26 15:16:35,585] WARN [missions-connector|task-0] [Producer clientId=gte_missions-schemahistory] Bootstrap broker *******.servicebus.windows.net:9093 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient:1065)
[2023-05-26 15:16:35,632] INFO [missions-connector|task-0] [Producer clientId=gte_missions-schemahistory] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:937)
[2023-05-26 15:16:35,632] INFO [missions-connector|task-0] [Producer clientId=gte_missions-schemahistory] Cancelled in-flight API_VERSIONS request with correlation id 583 due to node -1 being disconnected (elapsed time since creation: 16ms, elapsed time since send: 16ms, request timeout: 30000ms) (org.apache.kafka.clients.NetworkClient:341)
[2023-05-26 15:16:35,632] WARN [missions-connector|task-0] [Producer clientId=gte_missions-schemahistory] Bootstrap broker *******.servicebus.windows.net:9093 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient:1065)
[2023-05-26 15:16:35,710] INFO [missions-connector|task-0] [Producer clientId=gte_missions-schemahistory] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:937)
[2023-05-26 15:16:35,710] INFO [missions-connector|task-0] [Producer clientId=gte_missions-schemahistory] Cancelled in-flight API_VERSIONS request with correlation id 142 due to node -1 being disconnected (elapsed time since creation: 16ms, elapsed time since send: 16ms, request timeout: 30000ms) (org.apache.kafka.clients.NetworkClient:341)
[2023-05-26 15:16:35,710] WARN [missions-connector|task-0] [Producer clientId=gte_missions-schemahistory] Bootstrap broker *******.servicebus.windows.net:9093 (id: -1 rack: null) disconnected (org.apache.kafka.clients.NetworkClient:1065)
[2023-05-26 15:16:35,960] INFO [missions-connector|task-0] [Producer clientId=gte_missions-schemahistory] Node -1 disconnected. (org.apache.kafka.clients.NetworkClient:937)
```

Has it worked previously?
=========================
It works when I use a local Kafka Docker image.

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed or where adequate information has not been provided.

Please provide the relevant information for the following items:
 - [x] SDK (include version info): 
 ```java
java 19 2022-09-20
Java(TM) SE Runtime Environment (build 19+36-2238)
Java HotSpot(TM) 64-Bit Server VM (build 19+36-2238, mixed mode, sharing)
 ```
 - [ ] Sample you're having trouble with: 
 - [x] If using Apache Kafka Java clients or a framework that uses Apache Kafka Java clients, version: 2.2
 - [ ] Kafka client configuration: `<REPLACE with e.g., auto.reset.offset=earliest, ..>` (*do not include your connection string or SAS Key*)
 - [x] Namespace and EventHub/topic name : ept-cdc
 - [x] Consumer or producer failure : Both
 - [ ] Timestamps *in UTC* `<REPLACE with e.g., Nov 7 2018 - 17:15:01 UTC>`
 - [x] group.id or client.id _gte_missions-schemahistory_
 - [ ] Logs provided (with debug-level logging enabled if possible, e.g. log4j.rootLogger=DEBUG) or exception call stack
 - [ ] Standalone repro `<REPLACE with e.g., Willing/able to send scenario to repro issue>`
 - [x] Operating system: Windows 10 x64
 - [ ] Critical issue

If this is a question on basic functionality, please verify the following:
 - [x] Port 9093 should not be blocked by firewall ("broker cannot be found" errors)
 - [x] Pinging FQDN should return cluster DNS resolution (e.g. `$ ping namespace.servicebus.windows.net` returns ~ `ns-eh2-prod-am3-516.cloudapp.net [13.69.64.0]`)
 - [x] Namespace should be either Standard or Dedicated tier, not Basic (TopicAuthorization errors)

**Comment by hrishi-cog-coder** [comment]
@vincent1405 may I please know did you get any solution for this?

**Comment by l-t-k** [comment]
We are having the exact same issue with the exact same setup.

**Comment by hrishi-cog-coder** [comment]
Somehow managed resolve this.

1. Please create the schemahistory topic in event hub manually with cleanup policy as delete even before the connector creation
2. Please add below connector configurations
    "topic.creation.default.replication.factor":"1",
    "topic.creation.default.partitions":"1",
3. Run the connector config, It should create the individual topic automatically.
4. Please check the below linke if you have further questions or errors
    [https://debezium.zulipchat.com/#narrow/stream/302529-community-general/topic/.E2.9C.94.20error.20while.20creating.20connector](url)
5. If you wish to go with retries please add below connector configurations too
                "retries":"10",
		"errors.retry.timeout":"600000",
		"errors.retry.delay.max.ms":"30000",
		"errors.log.enable":"true",
		"errors.log.include.messages":"true",
		"errors.tolerance":"all"

**Comment by vincent1405** [comment]
Hi,

Thank you very much for your explanation and advices.
I decided to give up, and run a kafka instance near my on prem DB, then get the messages and push them to my domains.

Thank you

**Comment by shafaetkarim** [comment]
@hrishi-cog-coder ,
We having the same issue.. exact same error. Using docker for debezium ( version 2.3 ) and Azure Event hub ( standard ).
I have tried your advise to crate the “schema history” manually .. but having same behaviour!! Have been stuck with this for 3 days .. would you able to share your full solution ? Would be a lot of help mate ..

**Comment by hrishi-cog-coder** [comment]
@shafaetkarim  I was struggling for months. But finally managed to complete. Please follow the below steps.

1. Debezium documentation suggests creating a database schema history topic with infinite retention and no compaction. 
    [https://debezium.io/documentation/reference/stable/install.html#configuring-debezium-topics](url)
   Azure Event Hub standard does not support topic creation with infinite retention and no compaction.
2. So we have to use Azure Blob storage in this case. (There are additional options other than Azure Blob storage, [https://github.com/debezium/debezium/tree/main/debezium-storage](url), I have used Azure Blob Storage)
3. Please follow the link for saving schema history in Azure Blob Storage.
    [https://debezium.zulipchat.com/#narrow/stream/302529-community-general/topic/.E2.9C.94.20error.20while.20creating.20connector](url)
4. Please set the connector properties for Azure Blob Storage and copy and paste the mentioned jars to the /connect/debezium-connector-sqlserver path of debezium connect image. You may find the jars from the ZIP folder attached to the link (Please note that We have to download and use the jar versions correctly, You may find those from Maven Repository)

**Comment by shafaetkarim** [comment]
Thanks @hrishi-cog-coder.  It seems way more completed than we anticipated. I'm bit concern about the it's reliability with all these "custom" config and libs ( specially in PROD ). 
 But thanks a lot for your help mate.

**Comment by shafaetkarim** [comment]
Hi @hrishi-cog-coder 
We managed to get the  Debezium 2.3 + Event Hub running following all the useful details you shared. 
But I'm noticing this WARN log (   **Didn't reach end of config log quickly enough** ) in the connector, just wanted to check with you if you seen this in your case: 

```
       "schema.history.internal":"io.debezium.storage.azure.blob.history.AzureBlobSchemaHistory",
        "schema.history.internal.azure.storage.account.connectionstring":"",
        "schema.history.internal.azure.storage.account.container.name":"debezium-schema",
        "schema.history.internal.azure.storage.blob.name":"schema-history-connector1.json", 
```
		
**Log :**

```
2023-09-21 01:49:35,625 INFO   ||  [Worker clientId=connect-1, groupId=debezium-cluster-eventhub] Current config state offset 70 is behind group assignment 71, reading to end of config log   [org.apache.kafka.connect.runtime.distributed.DistributedHerder]
2023-09-21 01:49:38,625 WARN   ||  [Worker clientId=connect-1, groupId=debezium-cluster-eventhub] Didn't reach end of config log quickly enough   [org.apache.kafka.connect.runtime.distributed.DistributedHerder]
java.util.concurrent.TimeoutException: Timed out waiting for future
	at org.apache.kafka.connect.util.ConvertingFutureCallback.get(ConvertingFutureCallback.java:106)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore.refresh(KafkaConfigBackingStore.java:572)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.refreshConfigSnapshot(DistributedHerder.java:1625)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.readConfigToEnd(DistributedHerder.java:1606)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:378)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:352)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-09-21 01:49:38,626 INFO   ||  [Worker clientId=connect-1, groupId=debezium-cluster-eventhub] Resetting generation and member id due to: consumer pro-actively leaving the group   [org.apache.kafka.connect.runtime.distributed.WorkerCoordinator]
2023-09-21 01:49:46,126 INFO   ||  [Worker clientId=connect-1, groupId=debezium-cluster-eventhub] Current config state offset 70 is behind group assignment 71, reading to end of config log   [org.apache.kafka.connect.runtime.distributed.DistributedHerder]
2023-09-21 01:49:49,127 WARN   ||  [Worker clientId=connect-1, groupId=debezium-cluster-eventhub] Didn't reach end of config log quickly enough   [org.apache.kafka.connect.runtime.distributed.DistributedHerder]
java.util.concurrent.TimeoutException: Timed out waiting for future
	at org.apache.kafka.connect.util.ConvertingFutureCallback.get(ConvertingFutureCallback.java:106)
	at org.apache.kafka.connect.storage.KafkaConfigBackingStore.refresh(KafkaConfigBackingStore.java:572)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.refreshConfigSnapshot(DistributedHerder.java:1625)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.readConfigToEnd(DistributedHerder.java:1606)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.tick(DistributedHerder.java:378)
	at org.apache.kafka.connect.runtime.distributed.DistributedHerder.run(DistributedHerder.java:352)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2023-09-21 01:49:49,127 INFO   ||  [Worker clientId=connect-1, groupId=debezium-cluster-eventhub] Resetting generation and member id due to: consumer pro-actively leaving the group   [org.apache.kafka.connect.runtime.distributed.WorkerCoordinator]
2023-09-21 01:49:56,654 INFO   ||  [AdminClient clientId=debezium-cluster-eventhub--shared-admin] Node 3 disconnected.   [org.apache.kafka.clients.NetworkClient]
2023-09-21 01:49:56,655 INFO   ||  [AdminClient clientId=debezium-cluster-eventhub--shared-admin] Disconnecting from node 0 due to request timeout.   [org.apache.kafka.clients.NetworkClient]
2023-09-21 01:49:56,655 INFO   ||  [AdminClient clientId=debezium-cluster-eventhub--shared-admin] Cancelled in-flight METADATA request with correlation id 702 due to node 0 being disconnected (elapsed time since creation: 30030ms, elapsed time since send: 30030ms, request timeout: 30000ms)   [org.apache.kafka.clients.NetworkClient]
2023-09-21 01:49:56,656 INFO   ||  [AdminClient clientId=debezium-cluster-eventhub--shared-admin] Disconnecting from node 1 due to request timeout.   [org.apache.kafka.clients.NetworkClient]
2023-09-21 01:49:56,661 INFO   ||  [AdminClient clientId=debezium-cluster-eventhub--shared-admin] Cancelled in-flight METADATA request with correlation id 701 due to node 1 being disconnected (elapsed time since creation: 30030ms, elapsed time since send: 30030ms, request timeout: 30000ms)   [org.apache.kafka.clients.NetworkClient]
2023-09-21 01:49:56,661 INFO   ||  [AdminClient clientId=debezium-cluster-eventhub--shared-admin] Metadata update failed   [org.apache.kafka.clients.admin.internals.AdminMetadataManager]
org.apache.kafka.common.errors.TimeoutException: Call(callName=fetchMetadata, deadlineMs=1695260996624, tries=1, nextAllowedTryMs=1695260996761) timed out at 1695260996661 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.DisconnectException: Cancelled fetchMetadata request with correlation id 701 due to node 1 being disconnected
2023-09-21 01:49:59,127 INFO   ||  [Worker clientId=connect-1, groupId=debezium-cluster-eventhub] Current config state offset 70 is behind group assignment 71, reading to end of config log   [org.apache.kafka.connect.runtime.distributed.DistributedHerder]
2023-09-21 01:49:59,142 INFO   ||  [Worker clientId=connect-1, groupId=debezium-cluster-eventhub] Finished reading to end of log and updated config snapshot, new config log offset: 71   [org.apache.kafka.connect.runtime.distributed.DistributedHerder]
2023-09-21 01:49:59,142 INFO   ||  [Worker clientId=connect-1, groupId=debezium-cluster-eventhub] Rebalance started   [org.apache.kafka.connect.runtime.distributed.WorkerCoordinator]
2023-09-21 01:49:59,142 INFO   ||  [Worker clientId=connect-1, groupId=debezium-cluster-eventhub] (Re-)joining group   [org.apache.kafka.connect.runtime.distributed.WorkerCoordinator]
2023-09-21 01:50:02,152 INFO   ||  [Worker clientId=connect-1, groupId=debezium-cluster-eventhub] Successfully joined group with generation Generation{generationId=214, memberId='name-space.servicebus.windows.net:c:debezium-cluster-eventhub:I:connect-1-0bf399bee6c34702bf2b87ecfc97e21a', protocol='sessioned'}   [org.apache.kafka.connect.runtime.distributed.WorkerCoordinator]
2023-09-21 01:50:02,163 INFO   ||  [Worker clientId=connect-1, groupId=debezium-cluster-eventhub] Successfully synced group in generation Generation{generationId=214, memberId='name-space.servicebus.windows.net:c:debezium-cluster-eventhub:I:connect-1-0bf399bee6c34702bf2b87ecfc97e21a', protocol='sessioned'}   [org.apache.kafka.connect.runtime.distributed.WorkerCoordinator]
2023-09-21 01:50:02,164 INFO   ||  [Worker clientId=connect-1, groupId=debezium-cluster-eventhub] Joined group at generation 214 with protocol version 2 and got assignment: Assignment{error=0, leader='name-space.servicebus.windows.net:c:debezium-cluster-eventhub:I:connect-1-0bf399bee6c34702bf2b87ecfc97e21a', leaderUrl='http://internal.ip.address.0:8084/', offset=71, connectorIds=[connector1], taskIds=[connector1-0], revokedConnectorIds=[], revokedTaskIds=[], delay=0} with rebalance delay: 0   [org.apache.kafka.connect.runtime.distributed.DistributedHerder]
2023-09-21 01:50:02,164 INFO   ||  [Worker clientId=connect-1, groupId=debezium-cluster-eventhub] Starting connectors and tasks using config offset 71   [org.apache.kafka.connect.runtime.distributed.DistributedHerder]
2023-09-21 01:50:02,165 INFO   ||  [Worker clientId=connect-1, groupId=debezium-cluster-eventhub] Starting connector connector1   [org.apache.kafka.connect.runtime.distributed.DistributedHerder]
2023-09-21 01:50:02,165 INFO   ||  [Worker clientId=connect-1, groupId=debezium-cluster-eventhub] Starting task connector1-0   [org.apache.kafka.connect.runtime.distributed.DistributedHerder]
2023-09-21 01:50:02,165 INFO   ||  Creating task connector1-0   [org.apache.kafka.connect.runtime.Worker]
2023-09-21 01:50:02,165 INFO   ||  Creating connector connector1 of type io.debezium.connector.sqlserver.SqlServerConnector   [org.apache.kafka.connect.runtime.Worker]
2023-09-21 01:50:02,166 INFO   ||  ConnectorConfig values: 
	config.action.reload = restart
	connector.class = io.debezium.connector.sqlserver.SqlServerConnector
	errors.log.enable = true
	errors.log.include.messages = true
	errors.retry.delay.max.ms = 60000
	errors.retry.timeout = 0
	errors.tolerance = none
	header.converter = null
	key.converter = null
	name = connector1
	predicates = []
	tasks.max = 1
	transforms = []
	value.converter = null
   [org.apache.kafka.connect.runtime.ConnectorConfig]
```

**Comment by shafaetkarim** [comment]
I'm suspecting the error : **Didn't reach end of config log quickly enough** is due to the fact that we storing the internal.schema in Azure Blob shortage ( for 800+ tables), and the default timeout for the worker's WORKER_SYNC_TIMEOUT_MS is 3000 ... I think that 3s might not enough to read the schema and offsets from Blob.

Note that, this issue has been intermittent. I just increased this timeout today and will keep an eye on the test environment.

**Comment by hrishi-cog-coder** [comment]
I am sorry friend. I can not help much with this, but I suggest clearing all the components and restarting.
I think you have to connect with Chris Cranford or others through the Debezium Zulip community.

**Comment by shafaetkarim** [comment]
Hi @hrishi-cog-coder, 
Thanks.. but I have another question. I'm hosting Debezium ( v 2.3) in Azure Container Instance inside company VNet. But the connector endpoint are exposed to anyone within the VNet e.g. : http://{{debezium-server-ip}}:8083/connectors

I believe you have the similar situation... how you manage to "secure" those end point so that only "authorized" users within you company can execute those APIs ?

**Comment by senerope** [comment]
Thanks @hrishi-cog-coder for getting answers from debezium commuinity. 
The fact that this is not an issue with Kafka, Azure team for EventHubs should own this and provide documentation on the limitation of topics with Standard tier so that it is explicit. Like others my team has wasted many days figuring this out including debugging the debezium test classes for sql server connector.
MS has [this document](https://learn.microsoft.com/en-us/azure/event-hubs/event-hubs-kafka-connect-debezium) for setting up PostgreSQL connector (ironically not SQL Server) but here is no mention or warning related to the limitation of not being able to provide infinite retention for schema history topics in Standard tier and which properties to configure to be able to use Azure blob storage.

**Comment by hrishi-cog-coder** [comment]
@shafaetkarim 
We are using private Azure Kubernetes Service for deploying Debezium and it is not accessible from outside the AKS network. I do not know how to block or implement authorization for the connector endpoint. If you have some idea of solution please share.

**Comment by hrishi-cog-coder** [comment]
@senerope Yes. It will be better if Debezium has the documentation regarding the dependent jars file or the customized docker image directly available in the docker hub along with other Debezium images. Let me try to create a support ticket for the same in Debezium as well as Microsoft

**Comment by hrishi-cog-coder** [comment]
> I'm suspecting the error : **Didn't reach end of config log quickly enough** is due to the fact that we storing the internal.schema in Azure Blob shortage ( for 800+ tables), and the default timeout for the worker's WORKER_SYNC_TIMEOUT_MS is 3000 ... I think that 3s might not enough to read the schema and offsets from Blob.
> 
> Note that, this issue has been intermittent. I just increased this timeout today and will keep an eye on the test environment.

@shafaetkarim Hope you have already tried the configuration snapshot.mode = schema_only?

**Comment by jeacott1** [comment]
@hrishi-cog-coder eventhubs does support compact with infinite retention, but you need to use the kafka client to create them.
kafka connect manages to create its own configs, offset, and status eventhubs configured as compact/infinite. But as you say the history topics cannot create themselves. 
I can create a compact history eventhub like this:

from within a strimzi 4.10 image:

```
    local CLIENT_PROPS="/opt/kafka/custom-config/kafka-connect.properties"
    /opt/kafka/bin/kafka-topics.sh \
      --bootstrap-server "$BOOTSTRAP_SERVER" \
      --command-config "$CLIENT_PROPS" \
      --create \
      --topic "$topic" \
      --partitions 1 \
      --replication-factor 1 \
      --config cleanup.policy=compact \
      --config retention.ms=-1 \
      --config delete.retention.ms=86400000
```

However, I cannot get debezium to write to this topic. the producer always receives CORRUPT_MESSAGE errors.
It's been years, why did microsoft bother with the kafka api if it cant properly be used?
