### ISSUE TITLE
Example consumer for node.js fails on connection

### ISSUE THREAD

**Issue by IvanovOleg** [Azure/azure-event-hubs-for-kafka#73]
Description
===========
I tried to connect to my kafka enabled event hub and got an error:
```
{ Error: Broker: Inconsistent group protocol
    at Function.createLibrdkafkaError [as create] (C:\Users\user\Desktop\rdkafka\node_modules\node-rdkafka\lib\error.js:334:10)
    at C:\Users\user\Desktop\rdkafka\node_modules\node-rdkafka\lib\kafka-consumer.js:448:29
  message: 'Broker: Inconsistent group protocol',
  code: 23,
  errno: 23,
  origin: 'local' }
```
Example producer works fine.

How to reproduce
================
<How to reproduce the issue, or remove section if not relevant>

Has it worked previously?
=========================
<Is this a first attempt at getting the sample application to run, or has it worked in the past?>

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed or where adequate information has not been provided.

Please provide the relevant information for the following items:
 - [ ] SDK (include version info): `<REPLACE with e.g., kafka-python/Java SDK/confluent-kafka-dotnet with version info>`
 - [ ] Sample you're having trouble with: `<REPLACE with e.g., Java quickstart>`
 - [x] If using Apache Kafka Java clients or a framework that uses Apache Kafka Java clients, version: `<REPLACE with e.g., 1.1.0>`
 - [ ] Kafka client configuration: `<REPLACE with e.g., auto.reset.offset=earliest, ..>` (*do not include your connection string or SAS Key*)
 - [ ] Namespace and EventHub/topic name
 - [ ] Consumer or producer failure `<REPLACE with e.g., Consumer failure>`
 - [ ] Timestamps *in UTC* `<REPLACE with e.g., Nov 7 2018 - 17:15:01 UTC>`
 - [ ] group.id or client.id `<REPLACE with e.g., group.id=cg-name>`
 - [ ] Logs provided (with debug-level logging enabled if possible, e.g. log4j.rootLogger=DEBUG) or exception call stack
 - [ ] Standalone repro `<REPLACE with e.g., Willing/able to send scenario to repro issue>`
 - [ ] Operating system: `<REPLACE with e.g., Ubuntu 16.04.5 (x64) LTS>`
 - [ ] Critical issue

If this is a question on basic functionality, please verify the following:
 - [ ] Port 9093 should not be blocked by firewall ("broker cannot be found" errors)
 - [ ] Pinging FQDN shoudl return cluster DNS resolution (e.g. `$ ping namespace.servicebus.windows.net` returns ~ `ns-eh2-prod-am3-516.cloudapp.net [13.69.64.0]`)
 - [ ] Namespace should be either Standard or Dedicated tier, not Basic (TopicAuthorization errors)

**Comment by arerlend** [comment]
I was not able to reproduce.

Before I check traces, can you try running your node consumer on a new consumer group?  Inconsistent group protocol is most commonly returned if you have multiple consumers running on the same consumer group that don't share a common partition assignment protocol.  If this is the only consumer running on the group and you're receiving that error, then there is likely something to investigate.

**Comment by arerlend** [comment]
@IvanovOleg

**Comment by IvanovOleg** [comment]
@arerlend The problem appears when an application consumes messages from the multiple topics using the same consumer group name.

**Comment by arerlend** [comment]
Yes Event Hub consumer groups are totally different from Kafka consumer groups internally, so that part makes sense.

So the scenario is - single consumer reading from multiple topics with the same consumer group? Or multiple consumers, potentially multiple SDKs (not just node) reading from multiple topics with the same consumer group?

**Comment by IvanovOleg** [comment]
@arerlend We have an API gateway that accepts REST calls and sends them to multiple microservices using kafka messages, then expects replies from those microservices in multiple topics. Our API gateway is a consumer of multiple topics. When it is connected to a multiple topics using the same consumer group name ($Default, or any kind of name), the problem appears. As a workaround It connects to topics using `${topic_name}-api-gateway` pattern. I am wondering if the issue appear when we have more that one instance of the api-gateway running in parallel.

**Comment by arerlend** [comment]
Do you have a timestamp for the error?  I can check to see what condition is causing the service to throw.

**Comment by arerlend** [comment]
Check is currently not filled out btw.  Please fill it out so I have the info I need to investigate once I get a timestamp for the error.

**Comment by arerlend** [comment]
Closing due to inactivity.  Please reopen if needed.
