### ISSUE TITLE
fluentd - failed to flush the buffer - failed to assign partitions to 1 messages

### ISSUE THREAD

**Issue by Vincenttoolate** [Azure/azure-event-hubs-for-kafka#89]
Description
===========
failed to flush the buffer - failed to assign partitions to 1 messages

How to reproduce
================
td-agent.conf:
<source>
  @type tail
  path /var/log/messages
  pos_file /var/log/td-agent/messages.log.pos
  tag syslog.test
  <parse>
    @type syslog
  </parse>
</source>

<match syslog.**>
  @type kafka_buffered

  # list of seed brokers
  brokers <my-eventhub>.servicebus.windows.net:9093

  # buffer settings
  buffer_type file
  buffer_path /var/log/td-agent/buffer/kafka
  flush_interval 5s

  # topic settings
  default_topic TOPIC_NAME

  # data type settings
  output_data_type json

  # producer settings
  max_send_retries 1
  required_acks -1

  # using default OS certs for SSL
  ssl_ca_certs_from_system true

  username $ConnectionString
  password "Endpoint=sb://<my-eventhub>servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=<somekey>"
</match>

Has it worked previously?
=========================
It is the first attempt at getting the sample application to run

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed or where adequate information has not been provided.

Please provide the relevant information for the following items:

NOTE: I am using fluentd, most of the checklist might not relevant?

 - [ ] SDK (include version info): `<REPLACE with e.g., kafka-python/Java SDK/confluent-kafka-dotnet with version info>`
 - [ ] Sample you're having trouble with: `<REPLACE with e.g., Java quickstart>`
 - [x] If using Apache Kafka Java clients or a framework that uses Apache Kafka Java clients, version: `<REPLACE with e.g., 1.1.0>`
 - [ ] Kafka client configuration: `<REPLACE with e.g., auto.reset.offset=earliest, ..>` (*do not include your connection string or SAS Key*)
 - [ ] Namespace and EventHub/topic name
 - [ ] Consumer or producer failure `<REPLACE with e.g., Consumer failure>`
 - [ ] Timestamps *in UTC* `<2020-01-17 10:46:54 +1300>`
 - [ ] group.id or client.id `<REPLACE with e.g., group.id=cg-name>`
 - [ ] Logs provided (with debug-level logging enabled if possible, e.g. log4j.rootLogger=DEBUG) or exception call stack
2020-01-17 10:46:54 +1300 [info]: #0 initialized kafka producer: kafka
2020-01-17 10:46:54 +1300 [warn]: #0 failed to flush the buffer. retry_time=9 next_retry_seconds=2020-01-17 10:50:46 +1300 chunk="59c48b363214faa4e0bc359de998ddaa" error_class=Kafka::DeliveryFailed error="Failed to assign partitions to 1 messages"
  2020-01-17 10:46:54 +1300 [warn]: #0 suppressed same stacktrace
2020-01-17 10:50:48 +1300 [warn]: #0 Send exception occurred: Failed to assign partitions to 1 messages
2020-01-17 10:50:48 +1300 [warn]: #0 Exception Backtrace : /opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.10/lib/kafka/producer.rb:426:in `deliver_messages_with_retries'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.10/lib/kafka/producer.rb:253:in `block in deliver_messages'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.10/lib/kafka/instrumenter.rb:23:in `instrument'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/ruby-kafka-0.7.10/lib/kafka/producer.rb:246:in `deliver_messages'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kafka-0.12.2/lib/fluent/plugin/out_kafka_buffered.rb:288:in `deliver_messages'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluent-plugin-kafka-0.12.2/lib/fluent/plugin/out_kafka_buffered.rb:352:in `write'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/compat/output.rb:131:in `write'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/plugin/output.rb:1125:in `try_flush'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/plugin/output.rb:1431:in `flush_thread_run'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/plugin/output.rb:461:in `block (2 levels) in start'
/opt/td-agent/embedded/lib/ruby/gems/2.4.0/gems/fluentd-1.7.4/lib/fluent/plugin_helper/thread.rb:78:in `block in thread_create'

 - [ ] Standalone repro `<REPLACE with e.g., Willing/able to send scenario to repro issue>`
 - [ ] Operating system: `CentOS Linux release 7.7.1908 (Core)`
 - [ ] Critical issue

If this is a question on basic functionality, please verify the following:
 - [ ] Port 9093 should not be blocked by firewall ("broker cannot be found" errors)

[root@fluentd admin]# telnet test-fluentd.servicebus.windows.net 9093
`Trying 13.77.50.35...
Connected to test-fluentd.servicebus.windows.net.
Escape character is '^]'.`

 - [ ] Pinging FQDN shoudl return cluster DNS resolution (e.g. `[root@fluentd admin]# ping test-fluentd.servicebus.windows.net
PING ns-eh2-prod-ml1-506.cloudapp.net (13.77.50.35) 56(84) bytes of data.
`)
 - [ ] Namespace should be either Standard or Dedicated tier, not Basic (TopicAuthorization errors)

**Comment by arerlend** [comment]
Not sure how no one got to this.  @Vincenttoolate is this still an issue?
