### ISSUE TITLE
SALS authentification error

### ISSUE THREAD

**Issue by TheBiBi** [Azure/azure-event-hubs-for-kafka#99]
Description
===========
I have a problem with the SALS authentification.

**Return logs when i lauch ./connect-distributed.sh :**

`[2020-04-08 13:33:37,163] INFO [AdminClient clientId=adminclient-1] Failed authentication with kafkalog.servicebus.windows.net/23.100.14.185 (Invalid SASL mechanism response, server may be e
xpecting a different protocol) (org.apache.kafka.common.network.Selector:617)
[2020-04-08 13:33:37,167] WARN [AdminClient clientId=adminclient-1] Metadata update failed due to authentication error (org.apache.kafka.clients.admin.internals.AdminMetadataManager:235)
org.apache.kafka.common.errors.IllegalSaslStateException: Invalid SASL mechanism response, server may be expecting a different protocol
Caused by: org.apache.kafka.common.protocol.types.SchemaException: Error reading field 'auth_bytes': Bytes size -1 cannot be negative
at org.apache.kafka.common.protocol.types.Schema.read(Schema.java:110)
at org.apache.kafka.common.protocol.ApiKeys.parseResponse(ApiKeys.java:314)
at org.apache.kafka.clients.NetworkClient.parseStructMaybeUpdateThrottleTimeMetrics(NetworkClient.java:712)
at org.apache.kafka.clients.NetworkClient.parseResponse(NetworkClient.java:702)
at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.receiveKafkaResponse(SaslClientAuthenticator.java:514)
at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.receiveToken(SaslClientAuthenticator.java:448)
at org.apache.kafka.common.security.authenticator.SaslClientAuthenticator.authenticate(SaslClientAuthenticator.java:262)
at org.apache.kafka.common.network.KafkaChannel.prepare(KafkaChannel.java:173)
at org.apache.kafka.common.network.Selector.pollSelectionKeys(Selector.java:547)
at org.apache.kafka.common.network.Selector.poll(Selector.java:483)
at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:540)
at org.apache.kafka.clients.admin.KafkaAdminClient$AdminClientRunnable.run(KafkaAdminClient.java:1196)
at java.lang.Thread.run(Thread.java:748)`

**Config-contributed.properties file:**

`bootstrap.servers=kafkalog.servicebus.windows.net:9093
group.id=connect-cluster-group
config.storage.topic=connect-cluster-configs
offset.storage.topic=connect-cluster-offsets
status.storage.topic=connect-cluster-status
config.storage.replication.factor=1
offset.storage.replication.factor=1
status.storage.replication.factor=1
rest.advertised.host.name=connect
offset.flush.interval.ms=10000
key.converter=org.apache.kafka.connect.json.JsonConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter=org.apache.kafka.connect.json.JsonConverter
internal.value.converter=org.apache.kafka.connect.json.JsonConverter
internal.key.converter.schemas.enable=false
internal.value.converter.schemas.enable=false
security.protocol=SASL_SSL
sasl.mechanism=PLAIN
sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="kafkalog.servicebus.windows.net" password="Endpoint=sb://kafkalog.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=KEY";
producer.security.protocol=SASL_SSL
producer.sasl.mechanism=PLAIN
producer.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="kafkalog.servicebus.windows.net" password="Endpoint=sb://kafkalog.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=KEY";
consumer.security.protocol=SASL_SSL
consumer.sasl.mechanism=PLAIN
consumer.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="kafkalog.servicebus.windows.net" password="Endpoint=sb://kafkalog.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=KEY";

plugin.path=/opt/kafka_2.12-2.4.0/libs`

How to reproduce
================
Create a standard EventHub
Run a kafka on Ubuntu 18.04 with docker-compose

Has it worked previously?
=========================

No

Checklist
=========

**IMPORTANT**: We will close issues where the checklist has not been completed or where adequate information has not been provided.

 - [ x] Port 9093 should not be blocked by firewall ("broker cannot be found" errors)
 - [x ] Pinging FQDN shoudl return cluster DNS resolution (e.g. `$ ping namespace.servicebus.windows.net` returns ~ `ns-eh2-prod-am3-516.cloudapp.net [13.69.64.0]`)
 - [x ] Namespace should be either Standard or Dedicated tier, not Basic (TopicAuthorization errors)

**Comment by sjkwak** [comment]
@TheBiBi can you try again after updating username and setting the value of the username to '$ConnectionString'? Here is a link to the connector tutorial - https://github.com/Azure/azure-event-hubs-for-kafka/tree/master/tutorials/connect

**Comment by TheBiBi** [comment]
Hello @sjkwak, thank you to your answer.

I read back the documentation that you sent me.

And I have a question, the value of $ConnectionString is the same than the value request for the password ? 

Best Regards.
